[parity]
chain = "home/dogfooding/testnet-config/poaChainSpec.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[rpc]
hosts = ["all"]
cors = ["*"]
interface = "all"
port = 8540
apis = ["web3", "eth", "net"]
[websockets]
port = 8450
