[parity]
chain = "home/dogfooding/testnet-config/poaChainSpec.json"
base_path = "/tmp/parity0"
[network]
port = 30300
[account]
password = ["/home/node.pwds"]
[rpc]
hosts = ["all"]
cors = ["*"]
interface = "all"
port = 8540
apis = ["web3", "eth", "net"]
[websockets]
port = 8450
[mining]
engine_signer = "0x065230fa7ceaacc41879e8c4a8c854dde13eeca4"
reseal_on_txs = "none"
